# Generated by Django 5.1.3 on 2024-11-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='rate_value',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=18),
        ),
    ]
