# Generated by Django 5.1.3 on 2024-11-18 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_alter_currencyexchangerate_rate_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('api_key', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='currencyexchangerate',
            unique_together={('source_currency', 'exchanged_currency', 'valuation_date')},
        ),
    ]
