# Generated by Django 5.1.3 on 2024-11-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_exchangerateprovider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerateprovider',
            name='base_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
