# Generated by Django 5.1.3 on 2024-11-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_exchangerateprovider_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerateprovider',
            name='provider_class',
            field=models.CharField(choices=[('currencybeacon', 'Currency Beacon'), ('openexchangerates', 'Open Exchange Rates'), ('mock', 'Mock Provider')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
